version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/auth"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@twicetickets/common"
        versions: ["2.x"]

  - package-ecosystem: "npm"
    directory: "/expiration"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@twicetickets/common"
        versions: ["2.x"]

  - package-ecosystem: "npm"
    directory: "/orders"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@twicetickets/common"
        versions: ["2.x"]

  - package-ecosystem: "npm"
    directory: "/payments"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@twicetickets/common"
        versions: ["2.x"]

  - package-ecosystem: "npm"
    directory: "/tickets"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@twicetickets/common"
        versions: ["2.x"]
