services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - proxy
  auth:
    container_name: auth
    image: twiceboogie13/auth:latest
    ports:
      - "3001:3000"
    environment:
      - JWT_KEY=Random_Key_of_your_choice
      - MONGO_URI=mongodb://mongodb:27017/auth
    networks:
      - proxy
    depends_on:
      - mongodb
  expiration:
    container_name: expiration
    image: twiceboogie13/expiration:latest
    environment:
      - NATS_CLIENT_ID=expiration-first
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=ticketing
      - REDIS_HOST=expiration-redis
    networks:
      - proxy
    depends_on:
      - expiration-redis
  expiration-redis:
    container_name: expiration-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - proxy
  nats:
    container_name: nats
    image: nats-streaming:0.17.0
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-hbi"
      - "5s"
      - "-hbt"
      - "5s"
      - "-hbf"
      - "2"
      - "-SD"
      - "-cid"
      - "ticketing"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - proxy
  orders:
    container_name: orders
    image: twiceboogie13/orders:latest
    environment:
      - NATS_CLIENT_ID=orders-first
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=ticketing
      - MONGO_URI=mongodb://mongodb:27017/orders
      - JWT_KEY=Random_Key_of_your_choice
    ports:
      - "3002:3000"
    networks:
      - proxy
    depends_on:
      - mongodb
  payments:
    container_name: payments
    image: twiceboogie13/payments:latest
    environment:
      - NATS_CLIENT_ID=payments-first
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=ticketing
      - MONGO_URI=mongodb://mongodb:27017/payments
      - JWT_KEY=Random_Key_of_your_choice
      - STRIPE_KEY=<Your Stripe Key>
    ports:
      - "3003:3000"
    networks:
      - proxy
    depends_on:
      - mongodb
  tickets:
    container_name: tickets
    image: twiceboogie13/tickets:latest
    environment:
      - NATS_CLIENT_ID=tickets-first
      - NATS_URL=http://nats:4222
      - NATS_CLUSTER_ID=ticketing
      - MONGO_URI=mongodb://mongodb:27017/tickets
      - JWT_KEY=Random_Key_of_your_choice
    ports:
      - "3004:3000"
    networks:
      - proxy
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis-client
    ports:
      - 6378:6379
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
