apiVersion: skaffold/v4beta12
kind: Config
deploy:
  kubectl:
    defaultNamespace: development
build:
  local:
    push: false
  artifacts:
    - image: twiceboogie13/auth
      context: .
      docker:
        dockerfile: auth/Dockerfile
    - image: twiceboogie13/client
      context: .
      docker:
        dockerfile: web/Dockerfile
    - image: twiceboogie13/tickets
      context: .
      docker:
        dockerfile: tickets/Dockerfile
    - image: twiceboogie13/orders
      context: .
      docker:
        dockerfile: orders/Dockerfile
    - image: twiceboogie13/expiration
      context: .
      docker:
        dockerfile: expiration/Dockerfile
    - image: twiceboogie13/payments
      context: .
      docker:
        dockerfile: payments/Dockerfile

manifests:
  rawYaml:
    - ./infra/k8s/jwt-secret.yaml
    - ./infra/k8s/stripe-secret.yaml
    - ./infra/k8s/auth-depl.yaml
    - ./infra/k8s/auth-mongo-depl.yaml
    - ./infra/k8s/client-depl.yaml
    - ./infra/k8s/expiration-depl.yaml
    - ./infra/k8s/expiration-redis-depl.yaml
    - ./infra/k8s/ingress-srv.yaml
    - ./infra/k8s/nats-depl.yaml
    - ./infra/k8s/orders-depl.yaml
    - ./infra/k8s/orders-mongo-depl.yaml
    - ./infra/k8s/payments-depl.yaml
    - ./infra/k8s/payments-mongo-depl.yaml
    - ./infra/k8s/tickets-depl.yaml
    - ./infra/k8s/tickets-mongo-depl.yaml
