apiVersion: skaffold/v4beta12
kind: Config
deploy:
  kubectl:
    defaultNamespace: development
build:
  local:
    push: false
  artifacts:
    - image: twiceboogie13/auth
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          SERVICE_DIR: auth
      sync:
        manual:
          - src: "common/src/**/*.ts"
            dest: common
          - src: "auth/src/**/*.ts"
            dest: src
    - image: twiceboogie13/client
      context: web
      docker:
        dockerfile: Dockerfile
      sync:
        infer: ["**/*"]
    - image: twiceboogie13/tickets
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          SERVICE_DIR: tickets
      sync:
        manual:
          - src: "common/src/**/*.ts"
            dest: common
          - src: "tickets/src/**/*.ts"
            dest: src
    - image: twiceboogie13/orders
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          SERVICE_DIR: orders
      sync:
        manual:
          - src: "common/src/**/*.ts"
            dest: common
          - src: "orders/src/**/*.ts"
            dest: src
    - image: twiceboogie13/expiration
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          SERVICE_DIR: expiration
      sync:
        manual:
          - src: "common/src/**/*.ts"
            dest: common
          - src: "expiration/src/**/*.ts"
            dest: src
    - image: twiceboogie13/payments
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          SERVICE_DIR: payments
      sync:
        manual:
          - src: "common/src/**/*.ts"
            dest: common
          - src: "payments/src/**/*.ts"
            dest: src

manifests:
  rawYaml:
    - ./infra/k8s/jwt-secret.yaml
    - ./infra/k8s/stripe-secret.yaml
    - ./infra/k8s/auth-depl.yaml
    - ./infra/k8s/auth-mongo-depl.yaml
    - ./infra/k8s/client-depl.yaml
    - ./infra/k8s/expiration-depl.yaml
    - ./infra/k8s/expiration-redis-depl.yaml
    - ./infra/k8s/ingress-srv.yaml
    - ./infra/k8s/nats-depl.yaml
    - ./infra/k8s/orders-depl.yaml
    - ./infra/k8s/orders-mongo-depl.yaml
    - ./infra/k8s/payments-depl.yaml
    - ./infra/k8s/payments-mongo-depl.yaml
    - ./infra/k8s/tickets-depl.yaml
    - ./infra/k8s/tickets-mongo-depl.yaml
