import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { Suspense } from "react";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col h-screen dark:text-white dark:bg-gray-800">
            <Suspense>
              <Header />
            </Suspense>
            <div className="bg-purple-400 dark:bg-purple-800 flex items-center justify-center h-fit p-10 lg:h-screen">
              {children}
            </div>
          </div>
          {modal}
        </Providers>
      </body>
    </html>
  );
}
