import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GitTix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <Head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/@material-tailwind/html@latest/styles/material-tailwind.css"
        />
      </Head>
      <body
        className={`${inter.className} h-full bg-slate-300 dark:bg-slate-800`}
      >
        {children}
        {modal}
        <Script src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js" />
      </body>
    </html>
  );
}
